# Generated by Django 5.1.4 on 2025-01-04 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_technique_trend_alter_bait_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fish',
            name='locations',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
