services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend/react-frontend
      dockerfile: dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend

    documentation:
      build:
        context: ./documentation
        dockerfile: dockerfile
      ports:
        - "8001:8001"