# Generated by Django 5.1.4 on 2025-01-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('properties', models.TextField(blank=True, help_text='JSON-encoded list of properties')),
                ('notes', models.TextField(blank=True, help_text='JSON-encoded list of notes')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('properties', models.TextField(blank=True, help_text='JSON-encoded list of properties')),
                ('notes', models.TextField(blank=True, help_text='JSON-encoded list of notes')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('properties', models.TextField(blank=True, help_text='JSON-encoded list of properties')),
                ('notes', models.TextField(blank=True, help_text='JSON-encoded list of notes')),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('properties', models.TextField(blank=True, help_text='JSON-encoded list of properties')),
                ('notes', models.TextField(blank=True, help_text='JSON-encoded list of notes')),
            ],
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=100, unique=True)),
                ('trends', models.TextField(blank=True, help_text='JSON-encoded list of trends')),
                ('techniques', models.TextField(blank=True, help_text='JSON-encoded list of techniques')),
                ('tutorial_video', models.URLField(blank=True)),
                ('bait', models.ManyToManyField(related_name='fish', to='api.bait')),
                ('food', models.ManyToManyField(related_name='fish', to='api.food')),
                ('locations', models.ManyToManyField(related_name='fish', to='api.location')),
                ('structure', models.ManyToManyField(related_name='fish', to='api.structure')),
            ],
        ),
    ]
