# Generated by Django 5.1.4 on 2025-01-04 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bait',
            name='notes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bait',
            name='properties',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='fish',
            name='techniques',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='trends',
        ),
        migrations.AlterField(
            model_name='fish',
            name='tutorial_video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='notes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='properties',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='notes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='properties',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='structure',
            name='notes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='structure',
            name='properties',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='fish',
            name='techniques',
            field=models.ManyToManyField(related_name='fish', to='api.technique'),
        ),
        migrations.AddField(
            model_name='fish',
            name='trends',
            field=models.ManyToManyField(related_name='fish', to='api.trend'),
        ),
    ]
