site_name: Angler's Edge Documentation
nav:
  - Home: index.md
  - Backend:
    - Overview: backend/overview.md
    - Installation: backend/installation.md
  - Frontend:
    - Installation: frontend/installation.md
  - Testing:
    - Installation: testing/testing.md
theme: readthedocs
